### ISSUE TITLE
Xbox one?

### ISSUE THREAD

**Issue by wetoreoz** [simonferquel/Tidal-Unofficial-Win10#23]
Since Microsoft is gonna let developers submit UWA apps onto the Xbox store later this month. Is it possible you might submit Tidal?

**Comment by simonferquel** [comment]
This is one of my main focus area right now. However, due to some events in my personal life I have only a little time allocated to the project right now, but stay tuned :)

**Comment by simonferquel** [comment]
Here is a sneak preview of what is coming : 
![image](https://cloud.githubusercontent.com/assets/1677333/17594436/95063cce-5fe9-11e6-8795-d8c0f6c91f75.png)
The shell is nearly complete, still have some views to adapt for the game controller navigation but it is coming

**Comment by wetoreoz** [comment]
Excellent work man! I am very excited for this to come out. I'm just wondering is it going to be for preview members first or not and is there a expected date this might come out?

**Comment by simonferquel** [comment]
Latest version contains the Xbox UI and should appear shortly after the unified store is available on Xbox One :)
