### ISSUE TITLE
Says "waiting" and greyed out.

### ISSUE THREAD

**Issue by ghost** [simonferquel/Tidal-Unofficial-Win10#25]
Hi!

Nice app, my only concern is then I download load my big playlist, the app "locks" it self down after a day or two. I is not possible to start the app and the apps message is "waiting" and is greyed out. Both in app list and on startsscreen.. Only solution is to reinstall.. And ideas? :)

Best regards

Daniel

**Comment by simonferquel** [comment]
Hi,
could you make your playlist "public" and give me a link?

**Comment by ghost** [comment]
Sorry, that it took so long time..
Here's the link! :)

tidal.com/playlist/535b02d1-6ce1-440d-97cd-bc9121fe05ee

**Comment by ghost** [comment]
I think i have a clue on whats going on.. Please tell me if im out dreaming but i think it has not to do with the playlist itself. Im thinking that its just a coincidence. Im more thinking that it has to do with the app has not got "exclusive" rights to "sound chip" (or what the name could be) im observed now when I killed all the other apps and restarted the phone that tidal was working again.. Could this be and possibility? I for example have Spotify installed on the same phone and use it occasionally. I have not seen this behavior by other apps before.

**Comment by ghost** [comment]
When I opened the issue, I had just rebooted the phone one or two times and it was still grey and dead. That's why I was thinking of the playlist cause it happend when I had downloaded the playlist.. Sorry for the trouble..

**Comment by MarbleJH** [comment]
I have the same problem., Just be patient (Just Wait) and the app will be available after some time.

**Comment by simonferquel** [comment]
Seems to work fine with latest build (should appear on the store soon)
