### ISSUE TITLE
Is the app dead?

### ISSUE THREAD

**Issue by kevinboss** [simonferquel/Tidal-Unofficial-Win10#44]
I can't seem to find it in the store anymore. I guess it may very well be since it hasn't been updated for a year or so but is there a reason that it has been pulled from the store?

**Comment by lreneral** [comment]
same here, i couldnt also find it in the store. maybe the developer received a takedown notice!?

**Comment by yoyotogblo** [comment]
same here... would love to get the app

**Comment by cyanit** [comment]
ouch, just looked for the download as well
